# File: .config.yml | Note: Used to configure the Build Pipeline when deploying this Project
# Date: 30/08/2019 

version: 2.1 

commands:		
    build:
        steps: 
            - checkout 
            - run
                name: 	 Download Project Files & Install Dependencies
                command: npm install ci jsonlint remark-cli vsce
    lint:
        steps:
            - run 
                name: 	 Lint Project Markdown & JSON Files
                command: npm run lint
    package:
        steps:
            - run
                name: 	 Package up the VSIX File
                command: npm run build
            - store_artifacts:
                path: "snowstorm-theme.vsix"

jobs:
    snowstorm:
        docker: 
            - image: circleci/node:latest
        steps:
            - build
            - lint
            - package

worflows:
    version: 2
    build-project:
        triggers:
            - schedule:
                cron: "0 0 * * *"
                filters: 
                    branches:
                        only:
                            - build
        jobs:
            - snowstorm
                type:
                    - approval
