# File: .build.yml | Note: Used to configure the GitHub Actions Build Pipeline when deploying this Project
# Date: 07/12/2019 

name: Build Snowstorm Visual Studio Code VSIX File
on:
    push:
        branches:
            - build
    pull_request:
        types: [ opened ]

jobs:
    Snowstorm:
        name:       Build, Lint, & Package the Snowstorm Project
        runs-on:    windows-latest
        steps:
            - name: Download Snowstorm Git Project Files & Folders
              uses: actions/checkout@master

            - name: Download & Install the Project Dependencies
              uses: actions/setup-node@master
              with:
                  node-version: '10.x'

            - name: Install the NodeJS Dependencies & Files
              run:  npm install

            - name: Lint Project Markdown & JSON Files
              run:  npm run lint

            - name: Package up the VSIX File
              run:  npm run build

            - name: Upload Build Artifact
              uses: actions/upload-artifact@master
              with:
                  name: Snowstorm-VSIX
                  path: d:\a\Snowstorm\Snowstorm\snowstorm-color-theme.vsix

            - name: Publish Snowstorm Theme to Visual Studio Code Marketplace
              if:   github.ref == 'refs/heads/build'
              env: 
                  VS_CODE_SECRET: ${{ secrets.SNOWSTORM_VISUAL_STUDIO_CODE }}
              run:  vcse publish -p $VS_CODE_SECRET


